In [78]:
import pandas as pd 


In [80]:
data=pd.read_csv("C:/Users/Smart/Downloads/spam_ham_dataset.csv/spam_ham_dataset.csv")
data

,Unnamed: 0,label,text,label_num
0,605,ham,Subject: enron methanol ; meter # : 988291\r\n...,0
1,2349,ham,"Subject: hpl nom for january 9 , 2001\r\n( see...",0
2,3624,ham,"Subject: neon retreat\r\nho ho ho , we ' re ar...",0
3,4685,spam,"Subject: photoshop , windows , office . cheap ...",1
4,2030,ham,Subject: re : indian springs\r\nthis deal is t...,0
...,...,...,...,...
5166,1518,ham,Subject: put the 10 on the ft\r\nthe transport...,0
5167,404,ham,Subject: 3 / 4 / 2000 and following noms\r\nhp...,0
5168,2933,ham,Subject: calpine daily gas nomination\r\n>\r\n...,0
5169,1409,ham,Subject: industrial worksheets for august 2000...,0


In [82]:
data.tail()

,Unnamed: 0,label,text,label_num
5166,1518,ham,Subject: put the 10 on the ft\r\nthe transport...,0
5167,404,ham,Subject: 3 / 4 / 2000 and following noms\r\nhp...,0
5168,2933,ham,Subject: calpine daily gas nomination\r\n>\r\n...,0
5169,1409,ham,Subject: industrial worksheets for august 2000...,0
5170,4807,spam,Subject: important online banking alert\r\ndea...,1


In [84]:
data.describe()

,Unnamed: 0,label_num
count,5171.000000,5171.000000
mean,2585.000000,0.289886
std,1492.883452,0.453753
min,0.000000,0.000000
25%,1292.500000,0.000000
50%,2585.000000,0.000000
75%,3877.500000,1.000000
max,5170.000000,1.000000


In [86]:
data.duplicated().sum()

np.int64(0)

In [88]:
data.nunique()

Unnamed: 0    5171
label            2
text          4993
label_num        2
dtype: int64

In [90]:
data.isnull().sum()

Unnamed: 0    0
label         0
text          0
label_num     0
dtype: int64

In [92]:
data.drop(columns=['Unnamed: 0','label'],axis=1)

,text,label_num
0,Subject: enron methanol ; meter # : 988291\r\n...,0
1,"Subject: hpl nom for january 9 , 2001\r\n( see...",0
2,"Subject: neon retreat\r\nho ho ho , we ' re ar...",0
3,"Subject: photoshop , windows , office . cheap ...",1
4,Subject: re : indian springs\r\nthis deal is t...,0
...,...,...
5166,Subject: put the 10 on the ft\r\nthe transport...,0
5167,Subject: 3 / 4 / 2000 and following noms\r\nhp...,0
5168,Subject: calpine daily gas nomination\r\n>\r\n...,0
5169,Subject: industrial worksheets for august 2000...,0


In [94]:
X = data['text']
y = data['label_num']

In [96]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer


In [98]:
vecmodel=TfidfVectorizer(stop_words='english',
    lowercase=True,
    ngram_range=(1,2)
)
X_vec = vecmodel.fit_transform(X)
X_vec = pd.DataFrame.sparse.from_spmatrix(X_vec)# عشان تتعمل داتا فريم 


In [100]:
print(f"the new shape for x is {X_vec.shape}")
X_vec.head()

the new shape for x is (5171, 290990)


,0,1,2,3,4,5,6,7,8,9,...,290980,290981,290982,290983,290984,290985,290986,290987,290988,290989
0,0.054962,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


In [101]:
for i in range(5):
    print(sorted(list(X_vec.iloc[i,:]),reverse=True)[:20])
    print('--------------')

[np.float64(0.1600095833745749), np.float64(0.1600095833745749), np.float64(0.1600095833745749), np.float64(0.1600095833745749), np.float64(0.1600095833745749), np.float64(0.1600095833745749), np.float64(0.1600095833745749), np.float64(0.1600095833745749), np.float64(0.1600095833745749), np.float64(0.1600095833745749), np.float64(0.1600095833745749), np.float64(0.1600095833745749), np.float64(0.1600095833745749), np.float64(0.1600095833745749), np.float64(0.1600095833745749), np.float64(0.1600095833745749), np.float64(0.1600095833745749), np.float64(0.1600095833745749), np.float64(0.1600095833745749), np.float64(0.1600095833745749)]
--------------
[np.float64(0.5176224489804525), np.float64(0.5176224489804525), np.float64(0.3724132937367604), np.float64(0.20283772790612545), np.float64(0.1980536202414447), np.float64(0.19438634077496011), np.float64(0.1862066468683802), np.float64(0.1862066468683802), np.float64(0.1787287263074003), np.float64(0.13509812066058252), np.float64(0.1192967

In [104]:
x_train,x_test,y_train,y_test=train_test_split(X_vec,y,test_size=0.25,random_state=42)

In [105]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()

In [106]:
model.fit(x_train,y_train)

MultinomialNB()

In [107]:
y_pred=model.predict(x_test)

In [108]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test,y_pred)
accuracy

0.8785769528228925

In [109]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
cm

array([[930,   0],
       [157, 206]])

In [110]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.86      1.00      0.92       930
           1       1.00      0.57      0.72       363

    accuracy                           0.88      1293
   macro avg       0.93      0.78      0.82      1293
weighted avg       0.90      0.88      0.87      1293



In [111]:
from sklearn.linear_model import LogisticRegression

In [112]:
log_model =LogisticRegression(max_iter=1000,class_weight='balanced')

In [113]:
log_model.fit(x_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [114]:
y_pred_log = log_model.predict(x_test)

In [115]:
from sklearn.metrics import accuracy_score

accuracy_log = accuracy_score(y_test, y_pred_log)
accuracy_log

0.9520494972931168

In [116]:
from sklearn.metrics import confusion_matrix

cm_log = confusion_matrix(y_test, y_pred_log)
cm_log

array([[869,  61],
       [  1, 362]])

In [117]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_log))

              precision    recall  f1-score   support

           0       1.00      0.93      0.97       930
           1       0.86      1.00      0.92       363

    accuracy                           0.95      1293
   macro avg       0.93      0.97      0.94      1293
weighted avg       0.96      0.95      0.95      1293



In [134]:
from sklearn.svm import LinearSVC

svm_model = LinearSVC()
svm_model.fit(x_train, y_train)

y_pred = svm_model.predict(x_test)

In [136]:
from sklearn.metrics import accuracy_score
accuracy_svm=accuracy_score(y_test,y_pred)
accuracy_svm

0.991492652745553

In [138]:
from sklearn.metrics import confusion_matrix
svm_svm = confusion_matrix(y_test,y_pred)
svm_svm

array([[921,   9],
       [  2, 361]])

In [140]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       930
           1       0.98      0.99      0.98       363

    accuracy                           0.99      1293
   macro avg       0.99      0.99      0.99      1293
weighted avg       0.99      0.99      0.99      1293

